export const DefaultGameStore = {
  count: 0,
  deck: [],
  runningCount: 0,
  trueCount: 0,
  userAnswer: "",
  userTrueCountAnswer: "",
  suit: null,
  face: null,
  image: null,
  checkAnswerMode: false,
  correctAnswer: false,
  numberOfDecks: 1,
  dealerMode: "click",
  dealerDifficulty: null,
};
