export const DefaultGameStore = {
  count: 0,
  deck: [],
  runningCount: 0,
  trueCount: 0,
  userAnswer: 0,
  userTrueCountAnswer: 0,
  suit: null,
  face: 0,
  image: null,
  checkAnswerMode: false,
  correctAnswer: false,
  numberOfDecks: 1,
  dealerMode: "click",
};
